site_name: RDCP Protocol Specification
site_url: https://mojoatomic.github.io/rdcp-protocol/
site_description: Runtime Debug Control Protocol (RDCP) v1.0 - Language-agnostic specification for runtime debug control in distributed systems

# Repository
repo_url: https://github.com/mojoatomic/rdcp-protocol
repo_name: mojoatomic/rdcp-protocol
edit_uri: edit/main/

# Copyright
copyright: Copyright &copy; 2025 MojoAtomic

# Configuration
theme:
  name: material
  features:
    - navigation.instant
    - navigation.footer
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - content.action.edit
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode  
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Plugins
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      type: datetime
  - redoc-tag
  - swagger-ui-tag

# Extensions
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - admonition
  - attr_list
  - md_in_html
  - tables

# Extra
extra:
  version:
    provider: mike
    default: latest
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mojoatomic/rdcp-protocol

# Navigation
nav:
  - Home: index.md
  - Protocol Specification: rdcp-protocol-specification.md
  - Implementation Guide: rdcp-implementation-guide.md
  - Schemas:
    - Overview: schemas/index.md
    - Common Types: schemas/common.md
    - Protocol Discovery: schemas/endpoints/protocol-discovery.md
    - Control Request: schemas/endpoints/control-request.md
    - Control Response: schemas/endpoints/control-response.md
    - Discovery Response: schemas/endpoints/discovery-response.md
    - Status Response: schemas/endpoints/status-response.md
    - Health Response: schemas/endpoints/health-response.md
    - Error Response: schemas/responses/error.md
  - API:
    - Overview: api/index.md
    - Reference: api/reference.md
    - Playground: api/playground.md
  - Error Codes: error-codes.md
  - Compliance Kit:
    - Overview: compliance-kit/v1.0/README.md
    - Test Manifest: compliance-kit/v1.0/MANIFEST.md
    - Assertions: compliance-kit/v1.0/assertions.md
    - Running Tests: compliance-kit/v1.0/running-tests.md
  - Compliance Report: PROTOCOL-COMPLIANCE-REPORT.md
