site_name: RDCP Protocol Specification
site_url: https://mojoatomic.github.io/rdcp-protocol/
site_description: Runtime Debug Control Protocol (RDCP) v1.0 - Language-agnostic specification for runtime debug control in distributed systems

# Repository
repo_url: https://github.com/mojoatomic/rdcp-protocol
repo_name: mojoatomic/rdcp-protocol
edit_uri: edit/main/

# Copyright
copyright: Copyright &copy; 2025 MojoAtomic

# Configuration
theme:
  name: material
  features:
    - navigation.instant
    - navigation.footer
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - content.action.edit
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode  
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Plugins
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      type: datetime

# Extensions
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - admonition
  - attr_list
  - md_in_html
  - tables

# Extra
extra:
  version:
    provider: mike
    default: latest
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mojoatomic/rdcp-protocol

# Navigation
nav:
  - Home: index.md
  - Protocol Specification: rdcp-protocol-specification.md
  - Implementation Guide: rdcp-implementation-guide.md
  - Protocol Schemas: protocol-schemas.md
  - Error Codes: error-codes.md
  - Compliance Report: PROTOCOL-COMPLIANCE-REPORT.md