name: Deploy Documentation
on:
  push:
    branches:
      - main
  # Allow manual triggering
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
          
      - name: Set cache ID
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
        
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: ~/.cache
          restore-keys: |
            mkdocs-material-
            
      - name: Install dependencies
        run: |
          pip install mkdocs-material
          pip install mkdocs-git-revision-date-localized-plugin
          pip install mike
          
      - name: Deploy documentation with versioning
        run: |
          # Deploy the current version as 'latest' and '1.0'
          mike deploy --push --update-aliases 1.0 latest
          # Set latest as the default version
          mike set-default --push latest
