name: Validate OpenAPI

on:
  push:
    paths:
      - 'docs/api/**/*.json'
      - '.github/workflows/validate-openapi.yml'
  pull_request:
    paths:
      - 'docs/api/**/*.json'
      - '.github/workflows/validate-openapi.yml'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Lint (Redocly)
        run: |
          npx --yes @redocly/cli@latest lint docs/api/v1/openapi.json
