name: Validate OpenAPI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint OpenAPI spec
        run: npx @redocly/cli@latest lint docs/api/v1/openapi.json
